### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by caichuang0415** [ykarmesh/stable-control-representations#1]
Thanks for your great work, but how to run it ?

**Comment by ykarmesh** [comment]
Hi @caichuang0415, check out the readme in these folders: [Metaworld](https://github.com/ykarmesh/stable-control-representations/tree/main/cortexbench/mujoco_vc), [ImageNav](https://github.com/ykarmesh/stable-control-representations/tree/main/cortexbench/habitat_vc)
